const mongoose = require("mongoose");

/**
 * @swagger
 * components:
 *   schemas:
 *     User:
 *       type: object
 *       required:
 *         - email
 *         - password
 *       properties:
 *         _id:
 *           type: string
 *           description: Unique ID for the user (auto-generated by MongoDB)
 *           example: "65abc123ef456gh789ijkl"
 *         email:
 *           type: string
 *           description: Unique email of the user
 *           example: "user@example.com"
 *         password:
 *           type: string
 *           description: Hashed password of the user
 *           example: "$2b$10$X3jKfVJQ8LhW/NZzVpMgYeK/U5zA"
 */

const UserSchema = new mongoose.Schema(
  {
    email: { type: String, unique: true, required: true },
    password: { type: String, required: true }
  },
  { versionKey: false }
);

const userModel = mongoose.model("user", UserSchema);

module.exports = userModel;
